version: "3"

services:
  diet-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:11434"
    environment:
      - MODEL_URL=https://huggingface.co/XoXoHarsh/diet-assistant-llama3/resolve/main/unsloth.Q4_K_M.gguf?download=true
    restart: unless-stopped
    container_name: diet-ai

  # stress-ai:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8005:11434"
  #   environment:
  #     - MODEL_URL=https://huggingface.co/XoXoHarsh/stress-assistant-tinyllama/resolve/main/unsloth.Q4_K_M.gguf?download=true
  #   restart: unless-stopped
  #   container_name: stress-ai

  # exercise-ai:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8006:11434"
  #   environment:
  #     - MODEL_URL=https://huggingface.co/XoXoHarsh/exercise-assistant-tinyllama/resolve/main/unsloth.Q4_K_M.gguf?download=true
  #   restart: unless-stopped
  #   container_name: exercise-ai
