services:
  diet-assistant:
    build:
      context: .
      args:
        MODEL_NAME: ${MODEL1_NAME:-XoXoHarsh/diet-assistant-tinyllama}
    container_name: diet-assistant
    ports:
      - "11434:11434"
    environment:
      - MODEL_NAME=${MODEL1_NAME:-XoXoHarsh/diet-assistant-tinyllama}
      - OLLAMA_MODEL_NAME=${MODEL1_LOCAL_NAME:-diet-assistant-tinyllama}
      - MODEL_TYPE=${MODEL1_TYPE:-q4_k_m}
    volumes:
      - ollama-models-1:/root/.ollama
      - ./models/model1:/app/models
    restart: unless-stopped

  stress-assistant:
    build:
      context: .
      args:
        MODEL_NAME: ${MODEL2_NAME:-XoXoHarsh/stress-assistant-tinyllama}
    container_name: stress-assistant
    ports:
      - "11435:11434"
    environment:
      - MODEL_NAME=${MODEL2_NAME:-XoXoHarsh/stress-assistant-tinyllama}
      - OLLAMA_MODEL_NAME=${MODEL2_LOCAL_NAME:-stress-assistant-tinyllama}
      - MODEL_TYPE=${MODEL2_TYPE:-q4_k_m}
    volumes:
      - ollama-models-2:/root/.ollama
      - ./models/model2:/app/models
    restart: unless-stopped

  exercise-assistant:
    build:
      context: .
      args:
        MODEL_NAME: ${MODEL3_NAME:-XoXoHarsh/exercise-assistant-tinyllama}
    container_name: exercise-assistant
    ports:
      - "11436:11434"
    environment:
      - MODEL_NAME=${MODEL3_NAME:-XoXoHarsh/exercise-assistant-tinyllama}
      - OLLAMA_MODEL_NAME=${MODEL3_LOCAL_NAME:-XoXoHarsh/exercise-assistant-tinyllama}
      - MODEL_TYPE=${MODEL3_TYPE:-q4_k_m}
    volumes:
      - ollama-models-3:/root/.ollama
      - ./models/model3:/app/models
    restart: unless-stopped

  # diet-assistant-4:
  #   build:
  #     context: .
  #     args:
  #       MODEL_NAME: ${MODEL4_NAME:-XoXoHarsh/diet-assistant-llama3}
  #   container_name: diet-assistant-4
  #   ports:
  #     - "11437:11434"
  #   environment:
  #     - MODEL_NAME=${MODEL4_NAME:-XoXoHarsh/diet-assistant-llama3}
  #     - OLLAMA_MODEL_NAME=${MODEL4_LOCAL_NAME:-diet-assistant-4}
  #     - MODEL_TYPE=${MODEL4_TYPE:-q4_k_m}
  #   volumes:
  #     - ollama-models-4:/root/.ollama
  #     - ./models/model4:/app/models
  #   restart: unless-stopped

volumes:
  ollama-models-1:
  ollama-models-2:
  ollama-models-3:
  ollama-models-4:
